### ISSUE TITLE
Relate entries of same type?

### ISSUE THREAD

**Issue by hamishtaplin** [page-8/craft-manytomany#1]
Is there any way to relate entries of the same type to each other? For example, a channel of 'person' might have a 'spouse' field where you choose another person to relate. It'd be great if you could use this plugin to set up the two-way relationship but currently it only works across entry types.

Great work though, really useful!

**Comment by loweoj** [comment]
Hi guys, have you made any progress with this? I'm looking at exactly the same issue! Would love to have a peek at the beta if one's available?

Thanks!

**Comment by page-8** [comment]
I published the update to the dev branch. Please note, that this feature is definitely still in beta, so please use at your own risk.
