### ISSUE TITLE
Documentation could be a little clearer

### ISSUE THREAD

**Issue by loweoj** [page-8/craft-manytomany#3]
New self-managing relationships are great, thank you!
It took me a little while to figure out that you've added some settings to manage this - I was looking all over in the many-to-many fieldtype for an "add button" and trying combinations of fields to get it working. Maybe mention that the options of which you speak are inside new plugin settings! That would save some other unsuspecting folk some time.

Thanks again

**Comment by page-8** [comment]
Good call. Updated the docs.
