### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by matthisamoto** [page-8/craft-manytomany#31]
Hi, this modal window issue https://github.com/Pageworks/craft-manytomany/issues/24 has been fixed via PR https://github.com/Pageworks/craft-manytomany/pull/28 since middle 2019, but is not available through composer or on the Plugin Store. Can someone please tag a new release so that it gets updated? Thanks!

**Comment by jwrudzin** [comment]
Any update here? I'm waiting on this fix to be available via composer as well.

**Comment by bryantAXS** [comment]
Also running into this issue, a new tag would be great!

**Comment by engram-design** [comment]
Fixed in [2.0.0](https://github.com/verbb/many-to-many/releases/tag/2.0.0)
