### ISSUE TITLE
Latest version not available via Craft Plugins

### ISSUE THREAD

**Issue by frank-laemmer** [page-8/craft-manytomany#37]
Seems like the latest version of the plugin is not available with the Craft (Pixel & Tonic) Plugin store:

+ Version 1.0.2.2 -> https://plugins.craftcms.com/manytomany
+ Version 1.0.2.3 -> https://github.com/Pageworks/craft-manytomany

**Comment by engram-design** [comment]
Fixed in [2.0.0](https://github.com/verbb/many-to-many/releases/tag/2.0.0)
