### ISSUE TITLE
Craft 4 support?

### ISSUE THREAD

**Issue by CreateSean** [page-8/craft-manytomany#38]
Will this plugin be update to work with Craft 4?

**Comment by ostark** [comment]
@CreateSean 

Not fully tested, but it works for my limited use case
https://github.com/ostark/craft-manytomany/tree/craft4


Adjust your composer.json to use the fork for testing
```
// ...
  "require": {
    // ...
    "page-8/craft-manytomany": "dev-craft4"
  },
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/ostark/craft-manytomany"
    }
   ]


```
Any feedback is appreciated!

**Comment by ostark** [comment]
Damn, it worked for a while and now it does not save new relations.

**Comment by ostark** [comment]
It only works if `autosaveDrafts` is disabled in config/general.php 
That's probably related to the hidden `add` and `deleted` inputs ...

**Comment by engram-design** [comment]
Just to chime in, we've added this to our [Craft 3 migration project](https://verbb.io/craft-3), as people are keen to see this plugin on Craft 4.

If you're no longer developing this plugin, we'd be happy to continue development at Verbb (including updating to Craft 4). If you'd like to go ahead, you can transfer this repository to myself `engram-design` and we can take it from here.

**Comment by CreateSean** [comment]
Looks like this project is abandonware. Hoping that engram-design/verbb does update it. I have upvoted on the page linked above.

**Comment by engram-design** [comment]
Happy to take it over @CreateSean just haven't heard anything from any of the current maintainers @peter-tell @Wiejeben @monachilada

**Comment by codewithkyle** [comment]
@nickworks or @nicholashamilton might be able to help someone get in touch with @peter-tell

**Comment by peter-tell** [comment]
Well hi @codewithkyle !

Sorry for the delay all. I'm good with transferring this over.

**Comment by peter-tell** [comment]
Transferred. Thanks for taking this over @engram-design ! Looking forward to seeing what you guys do with it.

**Comment by engram-design** [comment]
@peter-tell Thanks for that, we'll get to work! 💪

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/many-to-many/releases/tag/3.0.0)
