### ISSUE TITLE
Adding and removing relations doesn't work.

### ISSUE THREAD

**Issue by dowadidi** [page-8/craft-manytomany#40]
### Describe the bug

The field shows the correct linked entries. But adding or removing relations, do not save.

### Steps to reproduce

1. Adding relations in section 1 to section 2 as normal.
2. Editing relations in the many-to-many field in section 2.

### Craft CMS version

4.3.10

### Plugin version

3.0.2

### Multi-site?

No

**Comment by ghost** [comment]
I  have the same issue 

Craft CMS 3.7.67
Many to Many 2.0.2

**Comment by engram-design** [comment]
I'm not actually full across the functionality of this plugin (just inherited it to keep it alive), but I've always thought the Many to Many field itself is essentially read-only? 

At least, that's what the code seems to point to, and that any changes to the field itself, adding elements has no real effect. Instead, it only shows what elements are related to the element containing the field.

Even going [back to before](https://github.com/verbb/many-to-many/tree/90a654ed2075adccdb271674c6a436311a878574) the `verbb/many-to-many` migration I can't see how it uses the values of the entries field itself for the field value.

But, happy to be proven wrong if there's functionality that used to work that now doesn't!

**Comment by dowadidi** [comment]
As seen in the screenshot in the readme 'Usage' section, step 4, it is suggested you can add and remove entries. Making at a usefull many to many field. At the moment, a twig field that lists the related entries, does the same trick.

Enabling adding and removing entries would be a great addition to the current functionality!
Otherwise, it might be a good idea to make the docs and ui reflect the current capabilities?

**Comment by engram-design** [comment]
I'll have to spin up the old version of the plugin just to double-check. Something may have just been lost in the migration to Craft 3/4 and fixing the outstanding issues with the field at the time.

**Comment by dowadidi** [comment]
Any news on this? :-)

**Comment by plcdnl** [comment]
Same problem. Is development still active?

**Comment by engram-design** [comment]
Should be fixed in [2.0.3](https://github.com/verbb/many-to-many/releases/tag/2.0.3) and  [3.0.3](https://github.com/verbb/many-to-many/releases/tag/3.0.3)
