### ISSUE TITLE
[craft-5] Parse error

### ISSUE THREAD

**Issue by d-karstens** [page-8/craft-manytomany#46]
### Describe the bug

Hi again,

Have just encountered a small issue upgrading to Craft 5, looks like it'd just be the `->` [here](https://github.com/verbb/many-to-many/blob/craft-5/src/services/Service.php#L101) and [here](https://github.com/verbb/many-to-many/blob/craft-5/src/services/Service.php#L121) 

![Screenshot 2024-03-06 at 5 17 14 pm](https://github.com/verbb/many-to-many/assets/21274925/8e5a83f1-343c-430c-b77f-de880fd40ff8)

### Steps to reproduce

1. Upgrade to Craft 5 beta
2. Attempt to access entry containing a Many to Many field

### Craft CMS version

5.0.0-beta.6 

### Plugin version

4.0.0-beta.1

### Multi-site?

No

**Comment by engram-design** [comment]
Fixed in [4.0.0-beta.2](https://github.com/verbb/many-to-many/releases/tag/4.0.0-beta.2)
